name: Build and Push Base Test Image

# trigger manually
on: workflow_dispatch

jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Build and Push Base Image
        env: 
          QUAY_ORG: ${{ secrets.QUAY_TEST_ORG }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN_TEST }}
        run: |
          cd e2e-tests
          podman login -u="$QUAY_ORG" -p="$QUAY_TOKEN" quay.io
          podman build -t quay.io/konflux_ui_qe/konflux-ui-tests-base:latest -f BaseContainerfile
          podman push quay.io/konflux_ui_qe/konflux-ui-tests-base:latest
